require("transparent").setup {
  groups = {
    "Normal",
    "NormalNC",
    "Constant",
    "Special",
    "Identifier",
    "Statement",
    "PreProc",
    "Type",
    "Underlined",
    "String",
    "Function",
    "Conditional",
    "Repeat",
    "Operator",
    "Structure",
    "LineNr",
    "NonText",
    "EndOfBuffer",
    "SignColumn",
  },
  extra_groups = { -- table/string: additional groups that should be cleared
    -- make floating windows transparent
    "LspFloatWinNormal",
    "Normal",
    "NormalFloat",
    "FloatBorder",
    "SagaBorder",
    "SagaNormal",
    "NormalFloat",
    "NvimTreeNormal",
    "NvimTreeNormalNC",
    "NvimTreeNormalFloat",
    "TroubleNormal",
    "GitSignsAdd",
    "GitSignsChange",
    "GitSignsDelete",
  },
  exclude_groups = {
    "Todo",
    "Comment",
    "StatusLine",
    "StatusLineNC",
    "CursorLine",
    "CursorLineNr",
    "CursorColumn",
  },
}
vim.g.transparent_groups = vim.list_extend(vim.g.transparent_groups or {}, { "ExtraGroup" })
