fork = false
frame = "transparent"
idle = true
maximized = false
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = false
# wsl = false

[font]
normal = ["Iosevka Nerd Font"]
size = 14
# hinting = "full"
edging = "antialias"
