# Get editor completions based on the config schema
# https://github.com/starship/starship/discussions/1107 some reference
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 10000

[directory]
truncation_length = 0
truncate_to_repo = false
