return {
  -- [[Task Runner]]
  -- TODO
  -- {
  --   "stevearc/overseer.nvim",
  --   lazy = true,
  --   enabled = false,
  --   key = {
  --     {
  --       "<leader>ot",
  --       "<cmd>OverseerToggle<cr>",
  --       desc = "Toggle task window",
  --     },
  --   },
  -- },

  --[[ LANGUAGE ]]
  -- Json
  {
    "b0o/schemastore.nvim",
    lazy = true,
    ft = { "jsonc", "json" },
    events = "VeryLazy",
  },

  -- TODO: if i need it or not.
  -- c/c++
  -- {
  --   "p00f/clangd_extensions.nvim",
  --   lazy = true,
  --   ft = { "c", "cpp", "objc", "objcpp", "h", "hpp" },
  --   config = function() end,
  --   opts = {
  --     inlay_hints = {
  --       inline = false,
  --     },
  --     ast = {
  --       --These require codicons (https://github.com/microsoft/vscode-codicons)
  --       role_icons = {
  --         type = "",
  --         declaration = "",
  --         expression = "",
  --         specifier = "",
  --         statement = "",
  --         ["template argument"] = "",
  --       },
  --       kind_icons = {
  --         Compound = "",
  --         Recovery = "",
  --         TranslationUnit = "",
  --         PackExpansion = "",
  --         TemplateTypeParm = "",
  --         TemplateTemplateParm = "",
  --         TemplateParamObject = "",
  --       },
  --     },
  --   },
  -- },

  -- -- ts/js
  -- {
  --   "JoosepAlviste/nvim-ts-context-commentstring",
  --   lazy = true,
  --   event = "BufReadPre",
  --   ft = { "html", "javascript", "typescript", "javascriptreact", "typescriptreact", "svelte", "vue" },
  --   config = function()
  --     require("ts_context_commentstring").setup({
  --       enable_autocmd = false,
  --     })
  --     require("Comment").setup({
  --       pre_hook = require("ts_context_commentstring.integrations.comment_nvim").create_pre_hook(),
  --     })
  --   end,
  -- },
  --
  -- -- C#
  -- {
  --   "seblyng/roslyn.nvim",
  --   ft = "cs",
  --   ---@module 'roslyn.config'
  --   ---@type RoslynNvimConfig
  --   opts = {},
  -- },
  --
  -- -- {
  -- --   "pmizio/typescript-tools.nvim",
  -- --   lazy = true,
  -- --   enabled = false,
  -- --   event = "BufReadPre",
  -- --   ft = { "html", "javascript", "typescript", "javascriptreact", "typescriptreact", "svelte", "vue" },
  -- -- },
  -- -- {
  -- --   "windwp/nvim-ts-autotag",
  -- --   lazy = true,
  -- --   enabled = false,
  -- --   event = "BufReadPre",
  -- --   ft = { "html", "javascript", "typescript", "javascriptreact", "typescriptreact", "svelte", "vue" },
  -- --   config = function()
  -- --     require("nvim-ts-autotag").setup({
  -- --       opts = {
  -- --         enable_close = false, -- Auto close tags
  -- --         enable_rename = true, -- Auto rename pairs of tags
  -- --         enable_close_on_slash = false, -- Auto close on trailing </
  -- --       },
  -- --       per_filetype = {
  -- --         ["html"] = {
  -- --           enable_close = false,
  -- --         },
  -- --       },
  -- --     })
  -- --   end,
  -- -- },
  --
  -- -- Maybe
  -- -- {
  -- --   "rmagatti/goto-preview",
  -- --   dependencies = { "rmagatti/logger.nvim" },
  -- --   event = "BufEnter",
  -- --   config = true,
  -- -- },
  --
}
