name: Linting and style check

on: [push, pull_request]

jobs:
  style:
    name: Fomatting and Linting
    runs-on: ubuntu-latest windows-latest macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.19.0
          # CLI arguments
          args: --color always --check .


